# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 02:45
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'name', unique=True, verbose_name='Slug')),
                ('ordering', models.SmallIntegerField(verbose_name=b'Ordering')),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'created',
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'name', unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('thank_you', models.TextField(verbose_name='Thank you text')),
                ('side_text', models.TextField(verbose_name='Side text')),
                ('organization_name_use', models.BooleanField(verbose_name='Use organization name field?')),
                ('first_name_use', models.BooleanField(verbose_name='Use first name field?')),
                ('second_name_use', models.BooleanField(verbose_name='Use second name field?')),
                ('place_use', models.BooleanField(verbose_name='Use place field?')),
                ('email_use', models.BooleanField(verbose_name='Use email field?')),
                ('active', models.BooleanField(verbose_name='Active status')),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'created',
                'verbose_name': 'Petition',
                'verbose_name_plural': 'Petitions',
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('organization_name', models.CharField(max_length=100, verbose_name='Organization')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('second_name', models.CharField(max_length=100, verbose_name='Second name')),
                ('place', models.CharField(max_length=100, verbose_name='Place')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signatures.Petition', verbose_name='Petition')),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'created',
                'verbose_name': 'Signature',
                'verbose_name_plural': 'Signatures',
            },
        ),
    ]
