# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0002_auto_20160921_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='signature',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='place',
            field=models.CharField(blank=True, max_length=100, verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='second_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Second name'),
        ),
    ]
