# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0003_auto_20160921_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='giodo_text',
            new_name='privacy_text',
        ),
    ]
