# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0004_auto_20160921_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='newsletter_text',
            field=models.TextField(blank=True, verbose_name='Newsletter aggrement'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='privacy_text',
            field=models.TextField(blank=True, verbose_name='Privacy aggrement'),
        ),
    ]
